AWSTemplateFormatVersion: '2010-09-09'
Description: GraalVM Example Stack
Transform: [ AWS::LanguageExtensions, AWS::Serverless-2016-10-31 ]

Resources:

  PostcodeLookupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/postcode-lookup
      Handler: uk.gov.di.ipv.cri.address.api.handler.PostcodeLookupHandler
      MemorySize: 512
      Runtime: provided.al2023
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
      Policies:
        - AWSLambdaBasicExecutionRole
    Metadata:
      BuildMethod: makefile

  PostcodeLookupFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PostcodeLookupFunction}
      RetentionInDays: 7